# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 10:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='category',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='leavetype',
            name='CL',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='EL',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='ML',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='RH',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='SCL',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leave',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.LeaveType'),
        ),
        migrations.AddField(
            model_name='leave',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
