# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_leavetype_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasualLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'My image',
            },
        ),
        migrations.CreateModel(
            name='EarnedLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MaternityLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RestrictedHoliday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialCasualLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='leavetype',
            name='category',
            field=models.IntegerField(choices=[(1, 'Casual Leave'), (2, 'Earned Leave'), (3, 'Maternity Leave'), (4, 'Special Casual Leave'), (5, 'Restricted Holiday')], default=1),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='CL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.EarnedLeave'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='EL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.CasualLeave'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='ML',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.MaternityLeave'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='RH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.RestrictedHoliday'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='SCL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.SpecialCasualLeave'),
        ),
    ]
