# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_auto_20170720_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casualleave',
            options={},
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='category',
        ),
    ]
