# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 11:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaves', '0006_auto_20170720_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='category',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='owner',
        ),
        migrations.AddField(
            model_name='leavetype',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='CL',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='EL',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='ML',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='RH',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='SCL',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CasualLeave',
        ),
        migrations.DeleteModel(
            name='EarnedLeave',
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
        migrations.DeleteModel(
            name='MaternityLeave',
        ),
        migrations.DeleteModel(
            name='RestrictedHoliday',
        ),
        migrations.DeleteModel(
            name='SpecialCasualLeave',
        ),
    ]
