# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0009_auto_20170720_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='CL',
            field=models.IntegerField(default=0, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='EL',
            field=models.IntegerField(default=0, verbose_name='el'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='ML',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='RH',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='SCL',
            field=models.IntegerField(default=0),
        ),
    ]
