# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 12:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0013_auto_20170720_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='CL',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
