# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0014_auto_20170720_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavetype',
            options={'verbose_name': 'Faculty List'},
        ),
    ]
