# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 14:59
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaves', '0015_auto_20170720_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='leavetype',
            options={'verbose_name': 'Faculty Name'},
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='CL',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='EL',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='ML',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(132), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='RH',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='SCL',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(default='No Name', max_length=120),
        ),
    ]
