# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0017_auto_20170720_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='designation',
            field=models.TextField(default='Assistant Professor', max_length=100),
        ),
    ]
