# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0018_auto_20170720_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hod',
            field=models.CharField(default='G Thippeswamy', max_length=35),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(default='Assistant Professor', max_length=100),
        ),
    ]
