# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 20:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaves', '0019_auto_20170720_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'CASUAL LEAVE'), (2, 'EARNED LEAVE'), (3, 'MATERNITY LEAVE'), (4, 'SPECIAL CASUAL LEAVE'), (5, 'RESTRICTED HOLIDAY')], default=1)),
                ('dateStart', models.DateField(default=datetime.date(2017, 7, 20))),
                ('dateEnd', models.DateField(default=datetime.date(2017, 7, 20))),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='static/profile/default.png', null=True, upload_to='static/profile/', verbose_name='profile picture'),
        ),
    ]
