# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0020_auto_20170720_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='static/profile/default.png', upload_to='static/profile/', verbose_name='profile picture'),
        ),
    ]
