# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 20:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0021_auto_20170720_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='CL',
            field=models.IntegerField(default=15, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='EL',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='ML',
            field=models.IntegerField(default=132, validators=[django.core.validators.MaxValueValidator(132), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='RH',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)]),
        ),
    ]
