# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0022_auto_20170720_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
