# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 12:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0026_templeavetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetaken',
            name='dateEnd',
            field=models.DateField(default=datetime.date(2017, 8, 6)),
        ),
        migrations.AlterField(
            model_name='leavetaken',
            name='dateStart',
            field=models.DateField(default=datetime.date(2017, 8, 6)),
        ),
    ]
